# See config.example.yml for documentation.
object_base: orig/GQNE5D
object: sys/main.dol
hash: ef001212c6cd4da3194c041d24956a61bc5e9fcd
symbols: config/GQNE5D/symbols.txt
splits: config/GQNE5D/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11